name: infra_did_dart
description: Infra DID Dart Library
version: 1.0.0
homepage: https://github.com/InfraBlockchain/infra-did-dart

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  eosdart: ^0.4.8
  eosdart_ecc: ^0.4.4
