name: infra_did_dart
description: Infra DID Dart Library
version: 1.0.0
homepage: https://github.com/InfraBlockchain/infra-did-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  bip39: ^1.0.6
  web3dart: ^2.3.5
  ethers: ^0.0.1+3
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.6.2
  dart_ssi: ^1.0.5
  ecdsa: ^0.0.4
  eosdart_ecc: ^0.4.4
  jose: ^0.3.3
  secp256k1: ^0.3.0
  http: ^0.13.4
  json_annotation: ^4.3.0
  pointycastle: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^7.2.10
  lints: ^2.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.infrablockchain.infra_did_dart
    pluginClass: InfraDidDartPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

ffigen:
  output: lib/bindings.dart
  headers:
    entry-points:
    - rust/target/bindings.h
  name: InfraDidDartBindings
  description: Dart bindings to call Infra DID functions
